#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Framework;
using OpenAccessModel3;


namespace OpenAccessModel3	
{
	[Table("Customers")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[Serializable()]
	public partial class Customer : NotificationObject
	{
		private string _customerID;
		[Column("CustomerID", OpenAccessType = OpenAccessType.UnicodeStringFixedLength, IsPrimaryKey = true, Length = 5, Scale = 0, SqlType = "nchar")]
		[Storage("_customerID")]
		public virtual string CustomerID 
		{ 
		    get
		    {
		        return this._customerID;
		    }
		    set
		    {
				if (this._customerID == value)
				{
					return;
				}
		
		        this._customerID = value;
				this.RaisePropertyChanged("_customerID");
		    }
		}
		
		private string _companyName;
		[Column("CompanyName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 40, Scale = 0, SqlType = "nvarchar")]
		[Storage("_companyName")]
		public virtual string CompanyName 
		{ 
		    get
		    {
		        return this._companyName;
		    }
		    set
		    {
				if (this._companyName == value)
				{
					return;
				}
		
		        this._companyName = value;
				this.RaisePropertyChanged("_companyName");
		    }
		}
		
		private string _contactName;
		[Column("ContactName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 30, Scale = 0, SqlType = "nvarchar")]
		[Storage("_contactName")]
		public virtual string ContactName 
		{ 
		    get
		    {
		        return this._contactName;
		    }
		    set
		    {
				if (this._contactName == value)
				{
					return;
				}
		
		        this._contactName = value;
				this.RaisePropertyChanged("_contactName");
		    }
		}
		
		private string _contactTitle;
		[Column("ContactTitle", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 30, Scale = 0, SqlType = "nvarchar")]
		[Storage("_contactTitle")]
		public virtual string ContactTitle 
		{ 
		    get
		    {
		        return this._contactTitle;
		    }
		    set
		    {
				if (this._contactTitle == value)
				{
					return;
				}
		
		        this._contactTitle = value;
				this.RaisePropertyChanged("_contactTitle");
		    }
		}
		
		private string _address;
		[Column("Address", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 60, Scale = 0, SqlType = "nvarchar")]
		[Storage("_address")]
		public virtual string Address 
		{ 
		    get
		    {
		        return this._address;
		    }
		    set
		    {
				if (this._address == value)
				{
					return;
				}
		
		        this._address = value;
				this.RaisePropertyChanged("_address");
		    }
		}
		
		private string _city;
		[Column("City", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 15, Scale = 0, SqlType = "nvarchar")]
		[Storage("_city")]
		public virtual string City 
		{ 
		    get
		    {
		        return this._city;
		    }
		    set
		    {
				if (this._city == value)
				{
					return;
				}
		
		        this._city = value;
				this.RaisePropertyChanged("_city");
		    }
		}
		
		private string _region;
		[Column("Region", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 15, Scale = 0, SqlType = "nvarchar")]
		[Storage("_region")]
		public virtual string Region 
		{ 
		    get
		    {
		        return this._region;
		    }
		    set
		    {
				if (this._region == value)
				{
					return;
				}
		
		        this._region = value;
				this.RaisePropertyChanged("_region");
		    }
		}
		
		private string _postalCode;
		[Column("PostalCode", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 10, Scale = 0, SqlType = "nvarchar")]
		[Storage("_postalCode")]
		public virtual string PostalCode 
		{ 
		    get
		    {
		        return this._postalCode;
		    }
		    set
		    {
				if (this._postalCode == value)
				{
					return;
				}
		
		        this._postalCode = value;
				this.RaisePropertyChanged("_postalCode");
		    }
		}
		
		private string _country;
		[Column("Country", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 15, Scale = 0, SqlType = "nvarchar")]
		[Storage("_country")]
		public virtual string Country 
		{ 
		    get
		    {
		        return this._country;
		    }
		    set
		    {
				if (this._country == value)
				{
					return;
				}
		
		        this._country = value;
				this.RaisePropertyChanged("_country");
		    }
		}
		
		private string _phone;
		[Column("Phone", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 24, Scale = 0, SqlType = "nvarchar")]
		[Storage("_phone")]
		public virtual string Phone 
		{ 
		    get
		    {
		        return this._phone;
		    }
		    set
		    {
				if (this._phone == value)
				{
					return;
				}
		
		        this._phone = value;
				this.RaisePropertyChanged("_phone");
		    }
		}
		
		private string _fax;
		[Column("Fax", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 24, Scale = 0, SqlType = "nvarchar")]
		[Storage("_fax")]
		public virtual string Fax 
		{ 
		    get
		    {
		        return this._fax;
		    }
		    set
		    {
				if (this._fax == value)
				{
					return;
				}
		
		        this._fax = value;
				this.RaisePropertyChanged("_fax");
		    }
		}
		
		private IList<Order> _orders = new List<Order>();
		[Collection(InverseProperty = "Customer")]
		[Storage("_orders")]
		public virtual IList<Order> Orders 
		{ 
		    get
		    {
		        return this._orders;
		    }
		}
		
		private IList<CustomerDemographic> _customerDemographics = new List<CustomerDemographic>();
		[Collection(InverseProperty = "Customers")]
		[Storage("_customerDemographics")]
		public virtual IList<CustomerDemographic> CustomerDemographics 
		{ 
		    get
		    {
		        return this._customerDemographics;
		    }
		}
		
	}
}
