#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Framework;
using OpenAccessModel3;


namespace OpenAccessModel3	
{
	[Table("Products")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	[Serializable()]
	public partial class Product : NotificationObject
	{
		private int _productID;
		[Column("ProductID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_productID")]
		public virtual int ProductID 
		{ 
		    get
		    {
		        return this._productID;
		    }
		    set
		    {
				if (this._productID == value)
				{
					return;
				}
		
		        this._productID = value;
				this.RaisePropertyChanged("_productID");
		    }
		}
		
		private string _productName;
		[Column("ProductName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 40, Scale = 0, SqlType = "nvarchar")]
		[Storage("_productName")]
		public virtual string ProductName 
		{ 
		    get
		    {
		        return this._productName;
		    }
		    set
		    {
				if (this._productName == value)
				{
					return;
				}
		
		        this._productName = value;
				this.RaisePropertyChanged("_productName");
		    }
		}
		
		private int? _supplierID;
		[Column("SupplierID", OpenAccessType = OpenAccessType.Int32, IsNullable = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_supplierID")]
		public virtual int? SupplierID 
		{ 
		    get
		    {
		        return this._supplierID;
		    }
		    set
		    {
				if (this._supplierID == value)
				{
					return;
				}
		
		        this._supplierID = value;
				this.RaisePropertyChanged("_supplierID");
		    }
		}
		
		private int? _categoryID;
		[Column("CategoryID", OpenAccessType = OpenAccessType.Int32, IsNullable = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_categoryID")]
		public virtual int? CategoryID 
		{ 
		    get
		    {
		        return this._categoryID;
		    }
		    set
		    {
				if (this._categoryID == value)
				{
					return;
				}
		
		        this._categoryID = value;
				this.RaisePropertyChanged("_categoryID");
		    }
		}
		
		private string _quantityPerUnit;
		[Column("QuantityPerUnit", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 20, Scale = 0, SqlType = "nvarchar")]
		[Storage("_quantityPerUnit")]
		public virtual string QuantityPerUnit 
		{ 
		    get
		    {
		        return this._quantityPerUnit;
		    }
		    set
		    {
				if (this._quantityPerUnit == value)
				{
					return;
				}
		
		        this._quantityPerUnit = value;
				this.RaisePropertyChanged("_quantityPerUnit");
		    }
		}
		
		private decimal? _unitPrice;
		[Column("UnitPrice", OpenAccessType = OpenAccessType.Currency, IsNullable = true, Length = 0, Scale = 0, SqlType = "money")]
		[Storage("_unitPrice")]
		public virtual decimal? UnitPrice 
		{ 
		    get
		    {
		        return this._unitPrice;
		    }
		    set
		    {
				if (this._unitPrice == value)
				{
					return;
				}
		
		        this._unitPrice = value;
				this.RaisePropertyChanged("_unitPrice");
		    }
		}
		
		private short? _unitsInStock;
		[Column("UnitsInStock", OpenAccessType = OpenAccessType.Int16, IsNullable = true, Length = 0, Scale = 0, SqlType = "smallint")]
		[Storage("_unitsInStock")]
		public virtual short? UnitsInStock 
		{ 
		    get
		    {
		        return this._unitsInStock;
		    }
		    set
		    {
				if (this._unitsInStock == value)
				{
					return;
				}
		
		        this._unitsInStock = value;
				this.RaisePropertyChanged("_unitsInStock");
		    }
		}
		
		private short? _unitsOnOrder;
		[Column("UnitsOnOrder", OpenAccessType = OpenAccessType.Int16, IsNullable = true, Length = 0, Scale = 0, SqlType = "smallint")]
		[Storage("_unitsOnOrder")]
		public virtual short? UnitsOnOrder 
		{ 
		    get
		    {
		        return this._unitsOnOrder;
		    }
		    set
		    {
				if (this._unitsOnOrder == value)
				{
					return;
				}
		
		        this._unitsOnOrder = value;
				this.RaisePropertyChanged("_unitsOnOrder");
		    }
		}
		
		private short? _reorderLevel;
		[Column("ReorderLevel", OpenAccessType = OpenAccessType.Int16, IsNullable = true, Length = 0, Scale = 0, SqlType = "smallint")]
		[Storage("_reorderLevel")]
		public virtual short? ReorderLevel 
		{ 
		    get
		    {
		        return this._reorderLevel;
		    }
		    set
		    {
				if (this._reorderLevel == value)
				{
					return;
				}
		
		        this._reorderLevel = value;
				this.RaisePropertyChanged("_reorderLevel");
		    }
		}
		
		private bool _discontinued;
		[Column("Discontinued", OpenAccessType = OpenAccessType.Bit, Length = 0, Scale = 0, SqlType = "bit")]
		[Storage("_discontinued")]
		public virtual bool Discontinued 
		{ 
		    get
		    {
		        return this._discontinued;
		    }
		    set
		    {
				if (this._discontinued == value)
				{
					return;
				}
		
		        this._discontinued = value;
				this.RaisePropertyChanged("_discontinued");
		    }
		}
		
		private Category _category;
		[ForeignKeyAssociation(ConstraintName = "FK_Products_Categories", SharedFields = "CategoryID", TargetFields = "CategoryID")]
		[Storage("_category")]
		public virtual Category Category 
		{ 
		    get
		    {
		        return this._category;
		    }
		    set
		    {
				if (this._category == value)
				{
					return;
				}
		
		        this._category = value;
				this.RaisePropertyChanged("_category");
		    }
		}
		
		private Supplier _supplier;
		[ForeignKeyAssociation(ConstraintName = "FK_Products_Suppliers", SharedFields = "SupplierID", TargetFields = "SupplierID")]
		[Storage("_supplier")]
		public virtual Supplier Supplier 
		{ 
		    get
		    {
		        return this._supplier;
		    }
		    set
		    {
				if (this._supplier == value)
				{
					return;
				}
		
		        this._supplier = value;
				this.RaisePropertyChanged("_supplier");
		    }
		}
		
		private IList<OrderDetail> _orderDetails = new List<OrderDetail>();
		[Collection(InverseProperty = "Product")]
		[Storage("_orderDetails")]
		public virtual IList<OrderDetail> OrderDetails 
		{ 
		    get
		    {
		        return this._orderDetails;
		    }
		}
		
	}
}
