//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IStringCount")]
public interface IStringCount
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCount/GetStringCount", ReplyAction="http://tempuri.org/IStringCount/GetStringCountResponse")]
    int GetStringCount(string containedString, string containeeString);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringCount/GetStringCount", ReplyAction="http://tempuri.org/IStringCount/GetStringCountResponse")]
    System.Threading.Tasks.Task<int> GetStringCountAsync(string containedString, string containeeString);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStringCountChannel : IStringCount, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StringCountClient : System.ServiceModel.ClientBase<IStringCount>, IStringCount
{
    
    public StringCountClient()
    {
    }
    
    public StringCountClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StringCountClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringCountClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StringCountClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int GetStringCount(string containedString, string containeeString)
    {
        return base.Channel.GetStringCount(containedString, containeeString);
    }
    
    public System.Threading.Tasks.Task<int> GetStringCountAsync(string containedString, string containeeString)
    {
        return base.Channel.GetStringCountAsync(containedString, containeeString);
    }
}
